apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: assystem
  name: assystem
spec:
  selector:
    matchLabels:
      io.kompose.service: assystem
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: assystem
    spec:
      containers:
      - image: assystem
        imagePullPolicy: Never
        name: assystem
        env:
          - name: SERVER_PORT
            value: '8080'        
        ports:
        - containerPort: 8080        
        resources: {}                
      restartPolicy: Always
status: {}
