apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ausystem
  name: ausystem
spec:
  selector:
    matchLabels:
      io.kompose.service: ausystem
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ausystem
    spec:
      containers:
      - image: ausystem
        imagePullPolicy: Never
        name: ausystem
        env:
          - name: SERVER_PORT
            value: '8081'        
        ports:
        - containerPort: 8081        
        resources: {}                
      restartPolicy: Always
status: {}
