apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: cesystem
  name: cesystem
spec:
  selector:
    matchLabels:
      io.kompose.service: cesystem
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cesystem
    spec:
      containers:
      - image: cesystem
        imagePullPolicy: Never
        name: cesystem
        env:
          - name: SERVER_PORT
            value: '8082'        
        ports:
        - containerPort: 8082        
        resources: {}                
      restartPolicy: Always
status: {}