apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  clusterIP: 10.96.5.6
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  type: LoadBalancer
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}
