apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: hrsystem
  name: hrsystem
spec:
  clusterIP: 10.96.5.3
  ports:  
  - name: "8083"
    port: 8083
    targetPort: 8083
  type: NodePort
  selector:
    io.kompose.service: hrsystem
